<?php
defined('BASEPATH') OR exit('No direct script access allowed');

// new

error_reporting(E_ALL);
ini_set("display_errors", 1);

$config = [
    'mode' => '-aCJK', 
    "autoScriptToLang" => true,
    "autoLangToFont" => true,
];

$mpdf = new \Mpdf\Mpdf($config);

$data = ob_start();

?>

<html>
<head>
	<meta charset="utf-8">
	<title><?php echo $student['fullname_en'] ?>-Ewallet</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC&display=swap" rel="stylesheet">

	<style type="text/css">

		body {
			margin: 0;
			padding: 0;
			font-family: 'Arial', 'Noto Sans SC', sans-serif!important;
			width: 210mm;
			min-height: 297mm;
			padding: 20mm;
			margin: 10mm auto;
			border: 1px solid black	;
			position: relative;
		}

		h1 {font-size: 24px;}
		h2 {font-size: 18px;}

		span {
			display: block;
			padding-top: 0.2rem;
			font-size: 14px;
		}
		
		td {
			vertical-align: top;
		}

	</style>
</head>
<body>
	<header>
		<table style="width: 100%;">
			<tr>
				<td style="vertical-align: middle; white-space: nowrap; width:90px;"><img src="<?php echo empty($image) ? 'https://cdn.synorex.link/assets/images/robocube/tuition.png' : $image; ?>" style="height: 100px; width: 100px;"></td>
				<td style="vertical-align: middle; padding-left: 1rem;">
					<h2 name="company-name"><?php echo $branch['title']; ?></h2>
					<span name="company-ssm">SSM: <?php echo empty($branch['ssm_no']) ? '-' : $branch['ssm_no'] ; ?></span><br>
					<span name="company-email">Email: <?php echo empty($branch['email']) ? '-' : $branch['email'] ; ?></span><br>
					<span name="company-tel">Phone: <?php echo empty($branch['phone']) ? '-' : $branch['phone'] ; ?></span><br>
					<span name="company-email">Address: <?php echo empty($branch['address']) ? '-' : $branch['address'] ; ?></span><br>
				</td>
				<td style="vertical-align: middle; text-align: right;">
					<h1>Ewallet</h1>
				</td>
			</tr>
			<tr>
				<td>
					<span></span><br>
					<span></span><br>
				</td>
			</tr>
			<tr>
				<td colspan="3">
					<span>Student</span><br>
					<span><b><?php echo $student['fullname_en']; ?></b></span><br>
					<span><?php echo empty($student['phone']) ? '-' : $student['phone']; ?></span>
				</td>
			</tr>
		</table>
		<br><br>
		<table style="width: 100%;">
			<tr>
				<th style="width: 15%; text-align: left;"><span>Date / Time</span></th>
				<th style="width: 30%; text-align: left;"><span>Details</span></th>
				<th style="width: 15%; text-align: right;"><span>Credit ($)</span></th>
				<th style="width: 15%; text-align: right;"><span>Debit ($)	</span></th>
				<th style="width: 15%; text-align: right;"><span>Amount ($)</span></th>
			</tr>
			<tr><td colspan="5"><hr style="margin: 0;"></td></tr>
			<?php
				
				$creditAmt = 0;
				$debitAmt = 0;
				$total = 0;

			foreach($log_point as $e) { 
				$creditAmt += $e['amount_1'];
				$debitAmt += $e['amount_0'];
				?>
				<tr style="border-bottom: 1px solid black;">
					<td><?php echo $e['create_on']; ?></td>
					<td>
						<?php echo $e['title']; ?>
						<span class="d-block small text-muted">Remark: <?php echo empty($e['remark']) ? '-' : $e['remark']; ?></span>
						<span class="d-block small text-muted">Create By: <?php echo empty($e['create_by']) ? '-' : datalist_Table('tbl_admins', 'nickname', $e['create_by']) ; ?></span>
					</td>
					<td style='text-align: right;'>
						<?php echo number_format($e['amount_1'], 2, '.', ','); ?>
					</td>
					<td style='text-align: right;'>
						<?php echo number_format($e['amount_0'], 2, '.', ','); ?>
					</td> 
					<td style='text-align: right;'>
						<?php $total += ($e['amount_1']-$e['amount_0']); ?>
						<?php echo number_format($total, 2, '.', ','); ?>
					</td>
				</tr>
				<?php
			}
			
			?>
		</table>
	</header>

	<footer style="position: absolute; bottom: 0;  padding: 20mm 20mm 10mm 0;">
		<table style="width: 100%;">
			<tr>
				<td colspan="5"><hr style="margin: 0;"></td>
			</tr>
			<tr>
				<td style="width: 15%; text-align: left;"><span>Total</span></td>
				<td style="width: 30%; text-align: left;"><span>&nbsp;</span></td>
				<td style="width: 15%; text-align: right;"><?php echo number_format($creditAmt, 2, '.', ','); ?></td>
				<td style="width: 15%; text-align: right;"><?php echo number_format($debitAmt, 2, '.', ','); ?></td>
				<td style="width: 15%; text-align: right;"><?php echo number_format(($creditAmt - $debitAmt), 2, '.', ','); ?></td>
			</tr>
		</table>
		<p><em>** This is auto generated by Robocube Tuition System on <?php echo date('M d, Y'); ?></em></p>
	</footer>
</body>
</html>

<?php

$data = ob_get_clean();


$mpdf->SetTitle('Ewallet.pdf');
$mpdf->WriteHTML($data);
$mpdf->Output('Ewallet.pdf', 'I');